### ISSUE TITLE
understand issue as a basic learners 

### ISSUE THREAD

**Issue by mani2care** [macadmins/nudge#120]
Hi Nice to have seen the projects and more hard work 

as a beginner unable to understand the process.

Kindly have any video about the project explained step by step and easier to learn and also use for us.

where to start and how to start what needs to be installed where the files to be transferred or how to build the pkg.

is nay thing wrong pls ignore

**Comment by erikng** [comment]
You cross posted this but it's very clear you haven't read the read me because there are prebuilt packages.

I am here to help but not to hand hold. Please read the documentation I have spent hours on and if you still have precise questions I can support you.

I also encourage you to join the macadmins slack channel where others using the tool are there.
