### ISSUE TITLE
Jamf Schema Json: Can not use "\n" in mainContentText

### ISSUE THREAD

**Issue by colorenz** [macadmins/nudge#168]
Hello,

"\n" don't work if you specify them through the Jamf Schema Json for mainContentText.

https://github.com/macadmins/nudge/blob/main/Schema/jamf/com.github.macadmins.Nudge.json

![image](https://user-images.githubusercontent.com/16665557/112354151-b0103000-8ccc-11eb-81aa-19feb8c901f1.png)

**Comment by erikng** [comment]
After talking with @talkingmoose about this, jamf currently does not allow option+enter or alt+enter to do new lines.

This was always my intended vision for Nudge profiles, but alas it is not to be. That said, again with JSON vs Profile, in the JSON you have to pass "\n" for new lines so it makes sense to support this in the profile.

I did some more investigation and found out that since Apple stores profile contents into a database, those databases convert "\n" to "\\n", which means "literal new line" and not "new line". The SwiftUI code then honors that and emits it as its literal string value.

I have gone ahead and fixed this and confirmed with the user it is working.

For non jamf pro users, I will continue to recommend not using the "\n" method within profiles and instead use an actual new line within the string itself.

The only caveat with my fix is now if people wanted to use a literal new line in their text field, it would be converted to a new line. I don't see any use-case for this, so I made an executive call.

**Comment by erikng** [comment]
Addressed with: https://github.com/macadmins/nudge/pull/169/commits/6bd6e4e6bc86df9731ce7b1baafa73ce4311b900
