### ISSUE TITLE
Sign Nudge with Developer ID Application certificate

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#177]
When viewing Nudge in Apparency, an error is generated because the app is signed with incorrect type of Apple developer certificate. This also causes Gatekeeper on some Macs to not launch the app.

The Apple Developer cert is used to sign apps destined for the Mac App Store. Instead, Nudge should be signed with a Developer ID Application certificate.

**Comment by natewalck** [comment]
I minted the fresh Developer App signing cert. The other version was an App Distribution cert, which is only for app store as mentioned. Thanks for mentioning this!

**Comment by erikng** [comment]
It took a few commits to get there: https://github.com/macadmins/nudge/commit/8796c576a4f7aae96332b594d44d203673e54e85 https://github.com/macadmins/nudge/commit/4fe4331ff9eb6f8533156650971a231fc4d33603 https://github.com/macadmins/nudge/commit/e2180df7056b25f7a843fc1c25f34c5cc00efd9d https://github.com/macadmins/nudge/commit/65e97ecdf645a2b29accbe5557b151b6cdf5c8af but I got it

1.0.0/1.0.1
<img width="1212" alt="Screen Shot 2021-08-18 at 3 15 30 PM" src="https://user-images.githubusercontent.com/5685016/129968642-e66346a0-ae5a-47f4-a14d-b7297db1a4c6.png">
1.1.0
<img width="1336" alt="Screen Shot 2021-08-18 at 3 34 34 PM" src="https://user-images.githubusercontent.com/5685016/129968679-479dff08-acc0-40a1-bf7c-3682d751f306.png">

It's still complaining about notarization, but I am going to track that https://github.com/macadmins/nudge/issues/216 since it's a different issue than what you asked for here.
