### ISSUE TITLE
Document all new v1.1.0 features and behaviors

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#217]
@erikng Are you able to list out all the new keys that have been added over the last couple of days in a comment here. Will make it much easier for me to add to the wiki rather than trawling through all the pull requests 😅

**Comment by erikng** [comment]
Yep will do tomorrow.

**Comment by erikng** [comment]
# New features
- `-debug-ui-mode` argument which shows both simpleMode and standardMode together in one Nudge window.
- When running Nudge in a Debug state, Nudge will not take focus when first opening.
- `showDeferralCount` preference for to enable/disable the deferral count in simpleMode and standardMode. `showDeferralCount` defaults to true to maintain v1.0 compatibility.
- Fix French and German localizations
- Flip `attemptToFetchMajorUpgrade` to true by default to allow major upgrades to Monterey and higher by default.
  - Major upgrades utilize `softwareupdate --fetch-full-installer` to download installers for Apple Silicon and Intel Macs. The logic also requires setting `majorUpgradeAppPath`.
  - Alternate major upgrade workflows will work if you pre-seed an `Install macOS.app` and configure `majorUpgradeAppPath` with the path. 
- Add Dutch (.nl) localization
- Created user quit deferral feature
  - `allowUserQuitDeferrals` is a new key in `userExperience` to enable this feature. By default it is set to `True` but can be set to `False` to keep Nudge v1.0.0 functionality
  - `customDeferralButtonText`, `oneDayDeferralButtonText`, and `oneHourDeferralButtonText` are new keys in `userInterface` -> `updateElements`. You can customize the text to your own needs, per localization.
  - `deferRunUntil` key is stored via NSUserDefaults (`~/Library/Preferences/com.github.macadmins.Nudge.plist`) to track when the next time Nudge should launch. Please note that Nudge when using this feature, Nudge will no longer adhere to your LaunchAgent logic as the user is opting to pick their own deferral time for the next nudge event.
  - `deferRunUntil` also uses UTC timestamps. There may be cases where the log event you view shows local time, where the Nudge event is in UTC time. This is expected behavior and is merely cosmetic.
- new key `actionButtonPath` that allows you to change the default behavior of the `updateDevice` button. This is useful if say you want to trigger a jamf self-service item with `jamfselfservice://remediate` or munki with `munki://updates` and any other URI you would like.
  -  When using this key, you will lose the dynamic capability for `updateDevice` supporting minor/major upgrades, so it will be up to your separate tool to handle thislogic.
- new key `acceptableApplicationBundleIDs` in `optionalFeatures` which allows you to disable nudge's re-activation logic if the application is being used by the user. This feature does not work for nudge's initial activation. If Nudge is not the foremost application, but one of these applications are, Nudge will not reactivate itself.
  - `"acceptableApplicationBundleIDs": ["us.zoom.xos", "com.apple.Safari"]`
  - Xcode is forced added to the acceptableApplicationsList when Nudge is running in debug mode.
- Nudge now displays negative integer numbers for `Days Remaining` field on simpleMode and standardMode. Prior functionality always showed `0`. The color also changes to bold/red once the number is negative.
- Nudge now calculates and maintains how many deferrals the user has performed per nudge event. With v1.0.0, Nudge would revert back to `0` deferrals after closing Nudge.
  - `requiredMinimumOSVersion`, `userSessionDeferrals`, `userQuitDeferrals` keys are stored via NSUserDefaults (`~/Library/Preferences/com.github.macadmins.Nudge.plist`) to track the deferrals per nudge event and reset them to 0 when a new nudge event has been deployed.
- Nudge now `exit 0` when closing the application rather than force AppKit to kill itself. This was causing rare crashing events.
- Nudge is now a signed (with `Developer ID Application`) and notarized application and the package is signed, notarized and stapled. Hardened Runtime is also enabled and timestamped codesigning, both requirements for notarization as of 2020.
  - Please note that for the application signature, it has now changed from team-id `PC74B3K3C2` to team-id `9GQZ7KUFR6`. The package signature remains on `9GQZ7KUFR6`.
- `additionalDeviceInfo` button (?) now properly shows the help/mouse icon when hovering over the button on simpleMode and standardMode
- Fixed various alignment issues/UI jumping in simpleMode when using dualQuitButtons.
- Close nudge when upgrading the package

**Comment by erikng** [comment]
new `targetedOSVersionsRule` key that allows multiple concurrent nudge events with various rules. `targetedOSVersions` is no longer honored in v1.1.0.
- `targetedOSVersionRule` is a simple string
  - If nudge finds a full match (device running 11.5.2, rule is 11.5.2), it will use the full match rules
  - if nudge finds a partial match (device running 11.5.2, rule is 11), it will use the partial match
  - if neither are found and there is a dictionary missing the targetedOSVersionsRule key, or the key has a value of "default", it will use them. This allows forward/backward compatibility with v1.0

If you need to have a configuration that works both for 1.0 and 1.1.0, please ensure that your "default" configuration is the very first item in the `osVersionRequirements` array.

```json
{
  "osVersionRequirements": [
    {
      "aboutUpdateURL": "https://apple.com",
      "requiredInstallationDate": "2021-07-30T00:00:00Z",
      "requiredMinimumOSVersion": "11.5.2",
      "targetedOSVersions": [
        "11.0",
        "11.0.1",
        "11.1",
        "11.2",
        "11.2.1",
        "11.2.2",
        "11.2.3",
        "11.3",
        "11.3.1",
        "11.4",
        "11.5",
        "11.5.1"
      ],
      "targetedOSVersionsRule": "default"
    },
    {
      "aboutUpdateURL": "https://apple.com",
      "requiredInstallationDate": "2021-07-30T00:00:00Z",
      "requiredMinimumOSVersion": "11.5.3",
      "targetedOSVersionsRule": "11.5.2"
    },
    {
      "aboutUpdateURL": "https://apple.com",
      "requiredInstallationDate": "2021-07-30T00:00:00Z",
      "requiredMinimumOSVersion": "11.5.4",
      "targetedOSVersionsRule": "11"
    }
  ]
}
```

**Comment by erikng** [comment]
The following wiki articles have been updated by myself and @dan-snelson
https://github.com/macadmins/nudge/wiki/optionalFeatures
https://github.com/macadmins/nudge/wiki/updateElements
https://github.com/macadmins/nudge/wiki/userExperience
https://github.com/macadmins/nudge/wiki/userInterface
https://github.com/macadmins/nudge/wiki/Preferences

I updated
https://github.com/macadmins/nudge/wiki/Command-Line-Arguments
https://github.com/macadmins/nudge/wiki/osVersionRequirements
https://github.com/macadmins/nudge/wiki/_Sidebar

I wrote new articles
https://github.com/macadmins/nudge/wiki/targetedOSVersionsRule
https://github.com/macadmins/nudge/wiki/User-Deferrals

**Comment by erikng** [comment]
https://github.com/macadmins/nudge/wiki/v1.1.0-features

I'm going to close this issue. @dan-snelson is making additional changes to some of these articles, but the broad design is complete.
