### ISSUE TITLE
Additional Device Information icon is out of alignment

### ISSUE THREAD

**Issue by smithjw** [macadmins/nudge#220]
The small question mark icon in the top-left of the Nudge UI is not in alignment with the corner.

![image](https://user-images.githubusercontent.com/916389/130169080-0bd4cf74-1304-4970-a000-ec382e4e07c6.png)

**Comment by erikng** [comment]
I've tried fixing that over and over and I can't figure out the right pixel coordinates that I'm happy with. I'll try it again.

**Comment by erikng** [comment]
This was incredibly tedious but I got it. https://github.com/macadmins/nudge/commit/75f709a1d58833630b0b84db0aa938f7860066b3

I can't guarantee it will not move since SwiftUI is dynamic, but with a basic configuration they are both centered.

standard
<img width="33" alt="Screen Shot 2021-08-20 at 11 55 24 AM" src="https://user-images.githubusercontent.com/5685016/130268212-0a79c7dc-e85f-4eab-8bb3-eaa7e54ac9c4.png">

simple
<img width="47" alt="Screen Shot 2021-08-20 at 11 56 16 AM" src="https://user-images.githubusercontent.com/5685016/130268262-abe041e3-3959-46ad-994a-d831cd13348a.png">
