### ISSUE TITLE
Point Nudge to specific update

### ISSUE THREAD

**Issue by Tomtenden3** [macadmins/nudge#279]
We are trying to get nudge to start a specific update like you can with the python verison by using /Applications/.app and we are using this with the actionbuttonpath, but we can't seem to get it to work, either Nudge just starts and closes or it closes right after you press the update button.
I can't find anything in the wiki that describes how to point nudge to the specific OS version, is there anything we are missing or is the swift version not able to upgrade from a local downloaded macOS version

**Comment by erikng** [comment]
This is possible, but there is a bug. This bug should be fixed with. https://github.com/macadmins/nudge/pull/284

In my testing the following configuration is sufficient to open `/Applications/Install macOS Monterey.app` if it exists. If you have the application in a different path you will have to set [majorUpgradeAppPath](https://github.com/macadmins/nudge/wiki/osVersionRequirements#majorupgradeapppath---type-string-default-value--required-no) as well.

```json
{
  "osVersionRequirements": [
    {
      "aboutUpdateURL": "https://google.com",
      "requiredInstallationDate": "2021-11-28T00:00:00Z",
      "requiredMinimumOSVersion": "12.0.1",
      "targetedOSVersionsRule": "default"
    }
  ],
  "userExperience": {
    "randomDelay": false
  },
  "userInterface": {
    "iconDarkPath": "/Library/Application Support/Nudge/logoDark.png",
    "iconLightPath": "/Library/Application Support/Nudge/logoLight.png",
    "screenShotDarkPath": "/Library/Application Support/Nudge/screenShotDark.png",
    "screenShotLightPath": "/Library/Application Support/Nudge/screenShotLight.png"
  }
}
```
