### ISSUE TITLE
Nudge 1.1.7.81395: opening in a desktop Space with a full screen app...

### ISSUE THREAD

**Issue by chilcote** [macadmins/nudge#365]
... results in the secondary Quit button, as well as the "additional device" button (the ? one) not functioning. Swiping to a different space and then interacting with Nudge will get those buttons to work.

https://user-images.githubusercontent.com/305026/170608141-d1f5512a-abe3-4663-8d95-346997feeb7a.mov

**Comment by erikng** [comment]
In my testing last month it was painfully obvious to me that apple has not tested apps launching on top of full screen apps.

I think what's happening here is a direct result of the behavior that nudge is coming up but did not take focus because of full screen. If it did, full screen would go away. 

The consequence is the stupid window still shows up. If you click back into the full screen app does nudge go away?

**Comment by chilcote** [comment]
Interestingly, the primary quit button works

**Comment by chilcote** [comment]
Also I tried 1.1.6.81329 (the shipping version we are using) and I don't have this problem. So it's a regression.

**Comment by erikng** [comment]
Yes, it's a regression from something I was trying to fix that I didn't like. I've resolved this regression and worked around the other bug I didn't like it.

https://github.com/macadmins/nudge/commit/6d882932f63adef2b1ccd589ea499217f36f99c9
