### ISSUE TITLE
Feature request: use system local time instead of time for a specific time zone (e.g., Z / GMT)

### ISSUE THREAD

**Issue by aysiu** [macadmins/nudge#386]
This would give users in different time zones across the globe more of a consistent experience. If the deadline is 10am on a particular Wednesday, then Nudge will hit that deadline for 10am for all users on Wednesday, whether that's Wednesday in Sydney, Australia; Wednesday in Mumbai, India; or Wednesday in Santiago, Chile.

**Comment by TheRossRoss** [comment]
I second this, as we just expanded our management of macOS devices to many other countries.

**Comment by MattR658** [comment]
In my testing, it seems that the "requiredInstallationDate" value does actually use the device's local time as opposed to UTC/Zulu, even though that UTC/Zulu is the format specified in the Nudge config. 

For example, if I configure "requiredInstallationDate" as: 2022-11-15T12:00:00Z in my config, this is acting as 12:00PM Noon across all my devices across different time zones. I'm not sure if this is the expected behavior, but wanted to report what I'm seeing.

To confirm, if I adjust the timezone manually on my device from EST to PST, it adjusts the "Hours Remaining To Update" field accordingly. If it were actually using UTC/Zulu, I would not expect this value to change based on my timezone and should stay static.

**Comment by erikng** [comment]
Tracking more here https://github.com/macadmins/nudge/issues/463
