### ISSUE TITLE
Timer vs LaunchAgent

### ISSUE THREAD

**Issue by groob** [macadmins/nudge#41]
Right now Nudge is going in the direction of a built-in timer, which would make the app also acts as a long running process. 
The alternative is to have Nudge be managed by a LaunchAgent with a StartInterval. The system state would be evaluated at an interval and the GUI would be opened only if necessary. 

There's pros/cons to both, but one of the advantages to a LaunchAgent is that it gives each admin a lot of flexibility to when the app is launched, without adding extra complexity to the code.

Thoughts?

**Comment by groob** [comment]
I haven't considered doing things while the App is active. That SGTM!

And to follow-up, why make it possible for the user to move nudge to the background anyway? We can make the app remain frontmost.

**Comment by abstertee** [comment]
Multiple screens makes the app remain on the one screen it was launched in.  The timer will help to reset the app window/view on the active monitor screen.

**Comment by erikng** [comment]
@groob so that question you pose may explain why your users wanted the option to defer (assuming it's always the active window).

If you look at some of the code I wrote this weekend, it can be problematic when nudge takes focus and there is a major update they are trying to click through or the system preferences. 

I loop through the active apps and if a user has an "acceptable app" we ignore the refresh.

**Comment by erikng** [comment]
I'm going to close this as I think I've adequately described my vision for this tool. If further enhancements want to be created, we can discuss in another ticket. There is a LaunchAgent that will be available in the next release through a separate package.

You can see that here: https://github.com/macadmins/nudge/pull/80
