### ISSUE TITLE
Feature Request: Nudge users to update Safari etc.

### ISSUE THREAD

**Issue by shoopdawoop** [macadmins/nudge#413]
Allow Nudge to specify minimum required versions of additional updates like "Safari16.1MontereyAuto-16.1" and "Safari16.1BigSurAuto-16.1".

Because, even after Nudge made them update to the latest macOS version, e.g. macOS 12.6.1, users might still keep using an older and potentially vulnerable version of Safari, e.g. 16.0.

**Comment by Nebula0000** [comment]
Assuming you have an MDM (Jamf for instance), it might be worth pushing out a **Software Update** "profile" (jamf: configuration profile), to enable: 

- Automatically Install App Updates from the App store 
- Automatically check for updates

This way, items like Safari are automatically updated and silently independent of Nudge

**Comment by donmontalvo** [comment]
Our experience has been once Nudge gets a user to update their macOS version, a second dialog comes up after the reboot, to tell the user that there's now an update to Safari. We haven't had to do anything for this to happen, it just does.

**Comment by erikng** [comment]
At this time I don't plan on supporting non macOS Updates to Nudge

**Comment by CorporateAbdul** [comment]
Would it be possible to rename this from Mac Admins Open Source to Nudge? The reason is because some end users might raise questions around what it is taking into consideration that Nudge communications are shared with macOS end users.

<img width="514" alt="Screenshot 2023-11-24 at 09 45 57" src="https://github.com/macadmins/nudge/assets/151910919/3b42b656-d974-4440-967d-515bb4fb7e30">
