### ISSUE TITLE
Nudge with 12.6 and 13 systems

### ISSUE THREAD

**Issue by stephanvanhienen** [macadmins/nudge#426]
Some of our machines are still running macOS 12 (a couple of systems don't support 13)
Is there anything we can do with Nudge for these systems ?
At the moment I can't set the required version to 13.0.1 since this would block older systems which can't upgrade to 13.

Any hints on this ?
Or should we create 2 config files for nudge based on the running macos version.

**Comment by colorenz** [comment]
Use two profiles one for clients which can install 13.x and one for clients which can only install 12.6.x..

**Comment by joeschlimmer-ic** [comment]
You can setup your configuration to have multiple required versions in an array.

like so

    <key>osVersionRequirements</key>
    <array>
      <dict>
        <key>requiredInstallationDate</key>
        <string>2022-11-24T00:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>11.7.1</string>
        <key>targetedOSVersionsRule</key>
        <string>11</string>
      </dict>
      <dict>
        <key>requiredInstallationDate</key>
        <string>2022-12-24T00:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>12.6.1</string>
        <key>targetedOSVersionsRule</key>
        <string>12</string>
      </dict>
      <dict>
        <key>requiredInstallationDate</key>
        <string>2021-12-241T00:00:00Z</string>
        <key>requiredMinimumOSVersion</key>
        <string>13.0.1</string>
        <key>targetedOSVersionsRule</key>
        <string>13.0</string>
      </dict>
    </array>
________________________________
From: stephanvanhienen ***@***.***>
Sent: Monday, December 12, 2022 10:30 AM
To: macadmins/nudge ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [macadmins/nudge] Nudge with 12.6 and 13 systems (Issue #426)

This message originated from outside the Ithaca College email system.


Some of our machines are still running macOS 12 (a couple of systems don't support 13)
Is there anything we can do with Nudge for these systems ?
At the moment I can't set the required version to 13.0.1 since this would block older systems which can't upgrade to 13.

Any hints on this ?
Or should we create 2 config files for nudge based on the running macos version.
