### ISSUE TITLE
Feature Request - Allow adding Change Freeze dates to config profile

### ISSUE THREAD

**Issue by n0brainer** [macadmins/nudge#427]
Not sure how feasible it would be, but it would be great if we could add our dates when we are in a change freeze and can't deploy any patches. Then nudge could look and see if those dates are true/false and act accordingly.

**Comment by erikng** [comment]
Interesting idea. I like it but yeah would take some thought here.

**Comment by bradtchapman** [comment]
@n0brainer : if you're able to use a configuration profile, you could remove Macs from scope during the change window.  

If you are managing this with a local JSON, you'll need to write a script that contains your change freeze dates and instruct it to unload the launch agent or do something else to disable Nudge.  

The danger of local administration is that you don't always know if it's going to work 100%.  Configuration profiles via MDM are more reliable.

**Comment by erikng** [comment]
I don't know how to implement this, so I'm going to close.

**Comment by BigMacAdmin** [comment]
I think I would implement this without any changes to Nudge.app code by using a wrapper script instead of the standard Nudge LaunchAgent.

Have your wrapper script look at a value in your Nudge profile to determine if it's within a "freeze date" or not. If not in the freeze date timeframe, then launch nudge just how the current LA does it.
