### ISSUE TITLE
Enhancement Request: Remote files for Icons and Screenshots

### ISSUE THREAD

**Issue by phillymjs** [macadmins/nudge#444]
Would it be possible to enable iconDarkPath, iconLightPath, screenShotDarkPath, and screenShotLightPath to use non-local files?

 e.g. 

```
<key>iconDarkPath</key>
	<string>https://assets.contoso.com/images/nudgeprod/companylogo.png</string>
<key>screenShotDarkPath</key>
	<string>https://assets.contoso.com/images/nudgeprod/macos1262screenshot.png</string>
```

The icon asset obviously doesn't change much, but the screenshot asset is updated for each OS version. Right now we have to deploy these assets out to our fleet ahead of changing the config profile to enforce an update, but if they could just be pulled from a central location when Nudge runs it would make life a lot easier.

**Comment by phillymjs** [comment]
If anyone else is looking for this feature, I achieved it with a script: https://github.com/phillymjs/get_nudge_assets

**Comment by erikng** [comment]
I have now implemented something that I think helps enough that this feature is no longer needed.

https://github.com/macadmins/nudge/issues/498

Due to Apple's refusal to back port SwiftUI features and my desire to continue to support macOS 11, I cannot implement web resources directly. While other macadmin tools like SwiftDialog have created hacks around this, I do not have the desire to do this, nor do I have the desire to use any 3rd party modules within Nudge.

**Comment by roberto2lini** [comment]
Since version 1.1.14.81545 is the final version that supports macOS 11. Would it be possible to re-consider this? It would be handy to load images over a HTTP Endpoint / S3 Bucket, that we can dynamically update on the clients without having to re-push the configuration XML with the base64 of a given image.

**Comment by erikng** [comment]
Nope because that feature in the way I want to implement requires at least macOS 12

**Comment by phillymjs** [comment]
@roberto2lini, take a look at this: https://gist.github.com/phillymjs/0839b664c99c6d9743afe8dcf34a5536

I wrote it a while back and used it until we switched to using generic screenshots that never need to change.

**Comment by erikng** [comment]
This has been addressed with https://github.com/macadmins/nudge/commit/1520f7bab0db4d719613b25decf34b3ab91355b5

The next pre-release of Nudge will contain this feature. I'm waiting for Github to release Xcode 15.3 before I can make a release.
