### ISSUE TITLE
Adjust the Size of the Optional Image

### ISSUE THREAD

**Issue by lhuffcaa** [macadmins/nudge#472]
When including an image to illustrate how to update, the user gets a very small image on the nudge window that's difficult to use. Clicking on it doesn't make it much larger. Maybe we can think of a way to make it more prominent and legible?

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/120140372/230120470-6709b62b-3880-4096-a7ca-fd2aa3b4f553.png">

<img width="1012" alt="image" src="https://user-images.githubusercontent.com/120140372/230120525-b7522265-9a86-4606-bf36-7953b8aa722d.png">

**Comment by bradtchapman** [comment]
Seconded.  There's a lot of wasted space.  Suggest scaling the image to fit the width of the nudge window and expand it to fit, but advise admins to design an image that is short and wide if possible.  

Recommend a maximum aspect ratio of 1:1 and a maximum apparent size in pixels / points (scale factor notwithstanding) so the image cannot become a vertical rectangle and scale the Nudge window to impossible heights.

**Comment by erikng** [comment]
I've tweaked this a bit on the upcoming build.

> so the image cannot become a vertical rectangle and scale the Nudge window to impossible heights.

This is indeed an issue and one I am not willing to cause, so the change I have made may not be good enough for your exact screenshot, but I don't think at this time I will tweak it any more.

If my upcoming change doesn't fix your issue, I would suggest changing your screen shot to have less horizontal and more vertical. In other words, stack them instead of placing them next to each other. I think that will allow you to have more usable window.
