### ISSUE TITLE
Feature Request: option to only rely on deferrals (not requiredInstallationDate)

### ISSUE THREAD

**Issue by smwaldman** [macadmins/nudge#473]
It would be awesome if there was an option to set allowedDeferrals to allow users to defer X amount of times, without setting a requiredInstallationDate. This would result in less overhead for the admin--rather than needing to change the deadline each time, we could simply increment the requiredOSVersion. The number of deferrals allowed could remain stagnant. This would also prevent accidents where someone forgets to change the requiredInstallationDate when incrementing the required os version.

**Comment by KWall24** [comment]
I'd was thinking that I'd appreciate being able to prioritize deferrals over the date, so that the prompts start based on the installation date, but after they start it's up to the user and how they defer. But I like your idea better. I'd be happy with either though, our users aren't in a position where we can force them to update on our schedule - they need to be on their schedule unless we want to interrupt classes, report cards, etc.

**Comment by smwaldman** [comment]
Love this!! Thank you!!!

Confirming that the true intent was to avoid manipulating the requiredInstallationDate (due to user error potential), and yes to remove the need to maintain the config. 

We also delay updates via profile, to avoid breaking bugs. Going to play with the new SOFA features, but since you mentioned that we can set SLA values, I think this will work perfectly. Thank you again!

**Comment by erikng** [comment]
There is also a key to prevent day 1 installations and delay by x amount of days but keep the SLA values. Definitely try it!
