### ISSUE TITLE
merge this repo (and all git history/prs/issues) into macadmins/nudge

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#50]
I'm not sure how this will work, but I want to merge this repo directly into there with all the git history.

It may not be possible, but if anyone knows, I'm interested. :)

**Comment by groob** [comment]
You can merge git histories, I've done it on projects in the past. https://stackoverflow.com/a/10548919
I suggest creating a new branch like `swift` or `v2` in the nudge repo and merging this remote into it. 

Issues/PRs and conversations will not be transfered, since that's part of GitHub not git. But since the repo was private and relatively new, IMO that's acceptable.

**Comment by erikng** [comment]
Yeah I've moved repos internally got retaining history and that's easy. I just wanted the issues and context. But you are right. Alternatively I could bring in the old code here and deprecate the old repo since no new features will be done to it.

**Comment by erikng** [comment]
This is now done.

the old project was renamed to https://github.com/macadmins/nudge-python
