### ISSUE TITLE
major vs minor SLA via Nudge

### ISSUE THREAD

**Issue by aanklewicz** [macadmins/nudge#593]
You asked me to put this as an issue, but you deleted the discussion, so I don't have what I wrote, so I will try to sum it up as best I can even though it's 12:30am.

We have different SLAs for major vs minor macOS releases. In our case it's 14 days for minor and 90 days for major. It would be nice if the upcoming 2.0 version's SOFA integration allows for delineating between major and minor. 

Though I understand if this extra bit is out of scope, but I wanted to put it in this any way. A part that would make this even better (for us), is if future minors that occur within the major SLA dates kept the same date, as users have 90 days to update to the new major from the initial release date of the new major. so if on day 30 macOS 15.0.1 is released it would keep the date as sequoiaReleaseDate+90days.

Thanks Erik for entertaining this idea, I really appreciate your hard work on this project.

**Comment by erikng** [comment]
Actually I ended up moving it https://github.com/macadmins/nudge/issues/591 and then closed discussions because I realized people weren't using issues. 

As said in the discussion I won't do the second part as it will get too complex too quickly. 

But the first portion is in the latest 2.0 release I issued last night. :)
