### ISSUE TITLE
Support for configurations stored on the web

### ISSUE THREAD

**Issue by GuillaumeRoss** [macadmins/nudge#60]
As to not break workflows of people using nudge-python with `--jsonurl`` - and to provide a way via which it is very easy to have source controlled configurations for Nudge, it would be great if the Swift version of Nudge also supported fetching the config file over https.

The file format does not have to be the same as previously, as it would be easy enough to point old Nudge python clients to one config and nudge-swift to new ones.

**Comment by erikng** [comment]
I'm going to mark this as a v1.1 feature for now because unless it's trivial, I need to focus on other features. Fetching is probably simple, but using a cache and offline mode is going to take more work. If you want to split these requests up, I can make the offline/cache mode a v1.1 and try and get the jsonurl in for v1.

**Comment by GuillaumeRoss** [comment]
Ok sounds good. I split them both in two, this one is for fetching the config, and the other one is for caching, if this here gets implemented. Thanks!

**Comment by erikng** [comment]
I'm going to try and have this in v1 of nudge

**Comment by erikng** [comment]
Support added. Check out #77 for how to use this.
