### ISSUE TITLE
alternative UIs from nudge python

### ISSUE THREAD

**Issue by erikng** [macadmins/nudge#63]
Because there was a nib before, people changed the content of nudge.

For people that have done that, please post screenshots here so we can discuss

**Comment by erikng** [comment]
<img width="962" alt="Nudge 2 1 5_redacted" src="https://user-images.githubusercontent.com/5685016/107685792-0750c880-6c6a-11eb-90eb-df2b1c1cb99d.png">

**Comment by xirianlight** [comment]
That's my screenshot above:

Main changes: 

Move call-to-action higher, set trigger to 'return' so that it's highlighted in blue for user interaction. Button positioning also more closely mimics System Preferences > Software Update

Moved some text to the left sidebar to eliminate textual clutter and users getting overwhelmed because reading is scary

Added a UI Box to the right side to help further separate the 'title' section from the 'body copy'

Added optional IMPORTANT text so that on computers where there's an available OS upgrade, text can clarify how to access the upDATES, which can often be very confusing. For this, I just changed paragraph 3 to have different properties and leave its value as "" if the current OS is detected.

Left-justified as much text as possible for visual continuity

Overlapped the "I Understand" and "Close buttons" - not visible here, but they populate the same space

Removed screenshot, opting instead for textual instructions - easier to maintain instead of supplying new screenshots per OS, just my personal preference for maintaining our setup

Added explanatory text to the More Info button to decrease support tickets asking if the popup was legit

**Comment by erikng** [comment]
<img width="962" alt="Screen Shot 2020-08-04 at 2 21 20 PM" src="https://user-images.githubusercontent.com/5685016/107686933-7844b000-6c6b-11eb-81e5-5dc1249622d1.png">

**Comment by erikng** [comment]
I thought about this over the day and I ended up liking it.

I made a new option called `simpleMode`

<img width="1012" alt="Screen Shot 2021-02-11 at 8 50 08 PM" src="https://user-images.githubusercontent.com/5685016/107725088-fc6a5800-6caa-11eb-9922-81b650a63da4.png">
<img width="1012" alt="Screen Shot 2021-02-11 at 8 50 20 PM" src="https://user-images.githubusercontent.com/5685016/107725093-fe341b80-6caa-11eb-8b29-53f992382af9.png">

**Comment by erikng** [comment]
@xirianlight I also like your UI. I may play around with this concept tomorrow.

**Comment by erikng** [comment]
![image](https://user-images.githubusercontent.com/5685016/107797793-f44cff80-6d20-11eb-9103-2692409c9617.png)
![image](https://user-images.githubusercontent.com/5685016/107797826-fca53a80-6d20-11eb-96b9-eda5699cee09.png)

some other UIs of forks

**Comment by erikng** [comment]
I've taken several elements and merged them all. I'm going to consider this done now, but here is where I landed.

<img width="1012" alt="Screen Shot 2021-02-12 at 5 38 56 PM" src="https://user-images.githubusercontent.com/5685016/107834159-1794a080-6d5b-11eb-81af-5bb015649869.png">
<img width="1012" alt="Screen Shot 2021-02-12 at 5 41 56 PM" src="https://user-images.githubusercontent.com/5685016/107834163-1bc0be00-6d5b-11eb-9ea8-35829806760d.png">
