### ISSUE TITLE
Caching of remote configuration

### ISSUE THREAD

**Issue by GuillaumeRoss** [macadmins/nudge#68]
If [issue 60 gets implemented](https://github.com/macadmins/nudge/issues/60) it would the configuration every time Nudge needs to run. When laptops are offline, that means Nudge can't execute properly.

Ideally, caching of the configuration would be built where it would be saved locally, and the latest configuration is pulled if available. If not available, the latest local cache is used, until the remote configuration becomes available next time.

**Comment by erikng** [comment]
After thinking about this, my view is this.

1. Nudge supports `.mobileconfiguration` to deploy via MDM which would support offline nudge events
2. Nudge supports a JSON installed to `/Library/Preferences` which would also support offline nudge events

The only case Nudge doesn't support it is with remote-url JSON. I think for now, I don't plan on implementing this as it will increase the code base and I will have to start maintaining a ~/Library/Cache just for this. I don't anticipate many nudge admins are doing it this way, so I think the effort/benefit is not weighted in the right direction.

My recommendation for this would be to actually use the mobileconfig option instead of the remote-json.
